// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiBridgeGreet(name: name);

String getDefaultCfg() => RustLib.instance.api.crateApiBridgeGetDefaultCfg();

List<String> getSheetNames({required String filePath}) =>
    RustLib.instance.api.crateApiBridgeGetSheetNames(filePath: filePath);

Future<String> update({
  required String cfgJson,
  required String excelPath,
  required String xmlDirPath,
}) => RustLib.instance.api.crateApiBridgeUpdate(
  cfgJson: cfgJson,
  excelPath: excelPath,
  xmlDirPath: xmlDirPath,
);

Future<String> quickUpdate({
  required String cfgJson,
  required String excelPath,
  required String xmlDirPath,
}) => RustLib.instance.api.crateApiBridgeQuickUpdate(
  cfgJson: cfgJson,
  excelPath: excelPath,
  xmlDirPath: xmlDirPath,
);
